### ISSUE TITLE
`#![cfg(not(test))]` in `lib.rs` breaks rust-analyzer

### ISSUE THREAD

**Issue by ShadowJonathan** [dalek-cryptography/ed25519-dalek#173] opened 2021-05-21 10:42 UTC
https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/src/lib.rs#L238

I found this while doing some scream tests to figure out what made rust-analyzer stop working.

**Comment by jnicholls** [comment] 2021-05-25 16:58
Yes since this was added in 1.0.1, rust-analyzer is not happy since it compiles everything in test mode, which is ideal as most people want their tests to be checked while authoring them all the same. Perhaps this cfg can be removed at the root module and added where it ought to be added throughout the crate, if necessary?

**Comment by isislovecruft** [comment] 2021-09-14 00:17
Hi @jnicholls, this should be fixed in the next release (1.1.0). Do you and/or rust-analyzer need it backported further?

**Closed by isislovecruft** 2021-09-14 00:17 UTC

**Comment by jnicholls** [comment] 2021-10-01 13:01
@isislovecruft Sorry for the delayed response. That is great news! I think it depends on what the 1.1.0 release contains. My personal stance is, I'll update to the 1.1 line. Those that have a requirement to limit change in their crypto code will probably continue to live with this as they have been. Putting myself in their shoes, if this is the only thing backported into a 1.0.2, that would be an appreciated update. If it's relatively trivial to backport, I'd vote for that 👍  Let me know if I can help.

**Comment by OfekShochat** [comment] 2021-11-17 10:36
hmm this isnt resolved yet but the issue is closed?

**Comment by damccull** [comment] 2021-12-07 20:53
Is there an ETA on when it will be in the crate? :) I'm excited to see this issue disappear.

**Comment by zicklag** [comment] 2022-02-15 20:58
If you want a quick fix that works right now you can add this to your VSCode settings file:

```json
"rust-analyzer.cargo.unsetTest": [
    "core",
    "ed25519-dalek"
  ],
```

This removes the `cfg(test)` flag from that crate while rust analyzer is building it.

**Comment by damccull** [comment] 2022-03-12 00:41
> If you want a quick fix that works right now you can add this to your VSCode settings file:
> 
> ```json
> "rust-analyzer.cargo.unsetTest": [
>     "core",
>     "ed25519-dalek"
>   ],
> ```
> 
> This removes the `cfg(test)` flag from that crate while rust analyzer is building it. `core` probably isn't necessary for this specific issue. I can't remember why I had that in there, but it fixes it for me, and you can add any other crates that have similar problems to that list, too.

Great solution. Thanks.

**Comment by g00nix** [comment] 2022-03-18 21:51
What's the solution for neovim? I tried this but it doesn't work:
```lua
require'lspconfig'.rust_analyzer.setup({  
    settings = {
        ["rust-analyzer"] = {
            cargo = {
              unsetTest = {             
                  "core", "ed25519-dalek", "curve25519-dalek"        
                }                       
            }                                  
        }                                      
    }                                          
})
```
